### ISSUE TITLE
Change in the "pull shark" badge

### ISSUE THREAD

**Issue by DevJourney19** [github-profile-achievements/spanish#14]
In my case to obtain the "pull shark" badge I had to make 19 pull requests, and not 16, do you think it is due to some github update? If so then it would be editing it.

**Comment by DevJourney19** [comment]
In my case to obtain the "pull shark" badge I had to make 19 pull requests, and not 16, do you think it is due to some github update? If so then it would be editing it.

**Comment by gomzyakov** [comment]
@DevJourney19 

I think GitHub simply doesn't issue badges right away, recalculating the numbers in background workers.
